##Script for evaluating VTR-TIMIT model output data

## This is another R script used to generate a report of the error of the formant estimates generated
## by a model, in comparison to the VTR-TIMIT F1-F3 reference values. It expects as input a single file
## in the format generated by get_report.sh; see that file for details.

## Like timitscript2.R, this script will also SMOOTH the data using a specified amount of
## binomial smoothing, in the form of 2 command line parameters: (a) the total number of smoothing
## rounds; and (b) how often to generate reports. It can be run e.g. as so:

## Rscript ../timitscript3.R timdb.mvt13.f6z1.txt 50 5 | sed "s:\[1\] ::" > timreport3.mvt13.f6z1.txt

## which instructs the script to generate a report after every 5 rounds of smoothing, for a total
## of 50 rounds (it also generates a pre-smoothed report). The amount of smoothing is indicated by a
## suffix, e.g. ".s5", appended to the end of every line in that section of the report. Hence, this
## script can be used to compare different amounts of smoothing. For the IS 2021 paper, we chose 10
## rounds of smoothing.

## The difference between timitscript2.R and this script is that this one generates statistics
## akin to those in Alku (2017), who reported their results primarily as "Formant Detection Rates" (FDRs),
## defined as the percentage of frames where the difference between the estimated formant frequency
## and the reference value is simultaneously less than a specified absolute value (e.g. 200 Hz)
## AND less than a specified percentage (e.g. 20%) of the reference value. That paper reported
## three different FDR specifications (Fest = estimated frequency; Fref = reference frequency):

## 1) |Fest - Fref| < 200 Hz AND |Fest - Fref| < 0.20 * Fref    (FDR20)
## 2) |Fest - Fref| < 250 Hz AND |Fest - Fref| < 0.25 * Fref    (FDR25)
## 3) |Fest - Fref| < 300 Hz AND |Fest - Fref| < 0.30 * Fref    (FDR30)

## so we calculate the same statistics here, as well as some mean absolute errors (MAEs)
## and mean percentage errors (MPEs).

## PREREQUISITES: Data files textdb2.txt and labels3.txt. See the README file
## for details about these files. To use the script, you'll need to edit the directory
## locations of those files listed below.


##fname = "timdb.mvt6.f6z2.txt"
args <- commandArgs(TRUE)
fname = args[1]
smooth = args[2]
mystep = args[3]

##Removes the first prefix from the filename (e.g. "timdb").
##The remaining name plus smoothing suffix is appended to all output lines.
x=strsplit(fname, ".", fixed=T)[[1]]
name=x[2]
for (i in 3:(length(x)-1)) name=paste0(name,".",x[i])

##Prerequisite files -- edit directory locations and filenames as needed
hand<-read.table("/home/lilley/nsfproject/data/textdb2.txt", header=F)
labs<-read.table("/home/lilley/nsfproject/data/labels3.txt", header=F)
#plabs<-read.table("/home/lilley/nsfproject/data/pitchlabs.txt", header=F)

df<-read.table(fname, header=F)


##Determines whether each frame is speech and in the same file as its neighboring rows.
r=nrow(hand)
samefile <- (hand[2:r,1] == hand[1:(r-1),1])
nonsil <- (labs[2:r,5] != "sil" & labs[1:(r-1),5] != "sil")
samefile2 = (samefile[1:(r-2)] & samefile[2:(r-1)])
nonsil2 = (nonsil[1:(r-2)] & nonsil[2:(r-1)])

##Mean absolute error
MAE <- function(df, vec, f) {
    mean(abs(hand[vec,f+8] - df[vec,f+2]))
}

##Mean percentage error
MPE <- function(df, vec, f) {
    mean(abs(hand[vec,f+8] - df[vec,f+2])/hand[vec,f+8]) * 100
}

##FDR for any specified percentage (tp) and absolute value (ta)
FDR <- function(df, vec, f, tp, ta) {
    diff = abs(hand[vec,f+8] - df[vec,f+2])
    mean(diff/hand[vec,f+8] < tp & diff < ta) * 100
}

##FDR at specified thresholds
FDR20 <- function(df, vec, f) { FDR(df, vec, f, 0.20, 200) }
FDR25 <- function(df, vec, f) { FDR(df, vec, f, 0.25, 250) }
FDR30 <- function(df, vec, f) { FDR(df, vec, f, 0.30, 300) }

##Get a row of the output table: specified statistic for
## specific data subset, broken down by formant and gender
getrow <- function(df, func, vec) {
      vec = (labs$V5!="sil" & hand$V2=="test" & vec)
      mal = (hand$V4 == "m" & vec)
      fem = (hand$V4 == "f" & vec)
      m1 = func(df,vec,1)
      m2 = func(df,vec,2)
      m3 = func(df,vec,3)
      res = c(mean(c(m1, m2, m3)), m1, m2, m3)
      m1 = func(df,mal,1)
      m2 = func(df,mal,2)
      m3 = func(df,mal,3)
      res = c(res, mean(c(m1, m2, m3)), m1, m2, m3)
      m1 = func(df,fem,1)
      m2 = func(df,fem,2)
      m3 = func(df,fem,3)
      res = c(res, mean(c(m1, m2, m3)), m1, m2, m3)
      res
}

## Pretty printing for percentage values
pprint <- function(df, name, label, func, vec) {
    print(noquote(paste(c(label, sprintf("%4.1f", getrow(df, func, vec)), name), collapse=" ")))
}

## Pretty printing for non-percentages
pprint2 <- function(df, name, label, func, vec) {
    print(noquote(paste(c(label, sprintf("%4.0f", getrow(df, func, vec)), name), collapse=" ")))
}


##Function to generate a complete report for a given model
report <- function(df, name) {
    print(noquote("                 ALL  F1   F2   F3  Male  MF1  MF2  MF3  Fem  FF1  FF2  FF3"))
    print(noquote("                ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----"))

    pprint2(df, name, " MAE   all tst:", MAE, vec=(labs$V5!="sil"))
    pprint2(df, name, " MAE vw|sv tst:", MAE, vec=(labs$V5=="vow" | labs$V5=="semi"))
    pprint2(df, name, " MAE vowel tst:", MAE, vec=(labs$V5=="vow"))
    pprint2(df, name, " MAE  semi tst:", MAE, vec=(labs$V5=="semi"))
    print("", quote=F)
    
    pprint(df, name, " MPE   all tst:", MPE, vec=(labs$V5!="sil"))
    pprint(df, name, " MPE vw|sv tst:", MPE, vec=(labs$V5=="vow" | labs$V5=="semi"))
    pprint(df, name, " MPE vowel tst:", MPE, vec=(labs$V5=="vow"))
    pprint(df, name, " MPE  semi tst:", MPE, vec=(labs$V5=="semi"))
    print("", quote=F)
    
    pprint(df, name, "DR20   all tst:", FDR20, vec=(labs$V5!="sil"))
    pprint(df, name, "DR20 vw|sv tst:", FDR20, vec=(labs$V5=="vow" | labs$V5=="semi"))
    pprint(df, name, "DR20 vowel tst:", FDR20, vec=(labs$V5=="vow"))
    pprint(df, name, "DR20  semi tst:", FDR20, vec=(labs$V5=="semi"))
    print("", quote=F)
    
    pprint(df, name, "DR25   all tst:", FDR25, vec=(labs$V5!="sil"))
    pprint(df, name, "DR25 vw|sv tst:", FDR25, vec=(labs$V5=="vow" | labs$V5=="semi"))
    pprint(df, name, "DR25 vowel tst:", FDR25, vec=(labs$V5=="vow"))
    pprint(df, name, "DR25  semi tst:", FDR25, vec=(labs$V5=="semi"))
    print("", quote=F)
    
    pprint(df, name, "DR30   all tst:", FDR30, vec=(labs$V5!="sil"))
    pprint(df, name, "DR30 vw|sv tst:", FDR30, vec=(labs$V5=="vow" | labs$V5=="semi"))
    pprint(df, name, "DR30 vowel tst:", FDR30, vec=(labs$V5=="vow"))
    pprint(df, name, "DR30  semi tst:", FDR30, vec=(labs$V5=="semi"))
    print("", quote=F)

}

name1=paste0(" ", name, ".F123")
name0=name1


## The following code checks to see if better results can be obtained by replacing
## one or more of the original formants F1-F3 with any of the higher formants. If a better
## configuration is found, the reports are generated for the amended model,
## rather than the original. The lines for the report will be appended with a suffix
## indicating the new formants used, e.g. "C134" would indicate that formants
## 1, 3, and 4 were used instead of 1-3.

## This was never the case for any of the models we trained with 6 formants. However, with
## models trained on more formants, we often found that the model would insert an
## extra formant between F1 and F2, or between F2 and F3. 


vec=(labs$V5!="sil")
best=10000
N=length(df)
for (i in 3:N)
    for (j in 3:N)
        for (k in 3:N) {
            if (i!=j && j!=k && i!=k) {
                rmse=sqrt(mean(c((hand[vec,9]-df[vec,i])^2, (hand[vec,10]-df[vec,j])^2, (hand[vec,11]-df[vec,k])^2)));
                if (rmse<best) {
                    best=rmse;
                    bestijk=c(i,j,k)
                }
            }
        };

if (sum(bestijk != c(3,4,5)) > 0) {
    df2=df
    df2[,3] = df[,bestijk[1]]
    df2[,4] = df[,bestijk[2]]
    df2[,5] = df[,bestijk[3]]
    name2=paste0(" ", name, ".C")
    for (i in 1:3) name2=paste0(name2, bestijk[i]-2)
    print(noquote(paste("Best corrected model:", name2, "(RMSE", best, ")")))
    print("", quote=F)
    name0=name2
    df=df2
}

## Generate a report for the unsmoothed data.
report(df, paste0(name0, ".s", 0))

## Smooth the data the specified number of rounds, and
## generate a report every _mystep_ rounds as specified.
for (i in 1:smooth) {
    df0=df[,3:5]
    r=nrow(df0)
    dfm1 = rbind(df0[1,], df0[1:(r-1),])
    dfp1 = rbind(df0[2:r,], df0[r,])
    df0 = 0.5*df0 + 0.25*dfm1 + 0.25*dfp1
    df = cbind(df[,1:2], df0)
    if (i %% as.integer(mystep) == 0 || i == smooth)
        report(df, paste0(name0, ".s", i))
}
