##Script for evaluating VTR-TIMIT model output data

## This is another R script used to generate a report of the error of the formant estimates generated
## by a model, in comparison to the VTR-TIMIT F1-F3 reference values. It expects as input a single file
## in the format generated by get_report.sh; see that file for details.

## Unlike timitscript.R, this script will also SMOOTH the data using a specified amount of
## binomial smoothing, in the form of 2 command line parameters: (a) the total number of smoothing
## rounds; and (b) how often to generate reports. It can be run e.g. as so:

## Rscript ../timitscript2.R timdb.mvt13.f6z1.txt 50 5 | sed "s:\[1\] ::" > timreport2.mvt13.f6z1.txt

## which instructs the script to generate a report after every 5 rounds of smoothing, for a total
## of 50 rounds (it also generates a pre-smoothed report). The amount of smoothing is indicated by a
## suffix, e.g. ".s5", appended to the end of every line in that section of the report. Hence, this
## script can be used to compare different amounts of smoothing. For the IS 2021 paper, we chose 10
## rounds of smoothing.

## The script generates the same statistics as timitscript.R,
## mostly MAEs (mean absolute errors) and RMSEs (root mean square errors)
## of various subsets of the data, and arranges them into tables for output. These
## data are meant to be comparable those found in the literature on VTR-TIMIT, e.g. Dissen et
## al. (2019) and Schiel & Zitzelberger (2018). The script also computes some measures
## of formant "jitter" (variance) and how often the formants cross each other.

## PREREQUISITES: Data files textdb2.txt, labels3.txt, and pitchlabs.txt. See the README file
## for details about these files. To use the script, you'll need to edit the directory
## locations of those files listed below.


##fname = "timdb.mvt6.f6z2.txt"
args <- commandArgs(TRUE)
fname = args[1]
smooth = args[2]
mystep = args[3]

##Removes the first prefix from the filename (e.g. "timdb").
##The remaining name plus smoothing suffix is appended to all output lines.
x=strsplit(fname, ".", fixed=T)[[1]]
name=x[2]
for (i in 3:(length(x)-1)) name=paste0(name,".",x[i])

##Prerequisite files -- edit directory locations and filenames as needed
hand<-read.table("/home/lilley/nsfproject/data/textdb2.txt", header=F)
labs<-read.table("/home/lilley/nsfproject/data/labels3.txt", header=F)
plabs<-read.table("/home/lilley/nsfproject/data/pitchlabs.txt", header=F)

df<-read.table(fname, header=F)


##Determines whether each frame is speech and in the same file as its neighboring rows.
r=nrow(hand)
samefile <- (hand[2:r,1] == hand[1:(r-1),1])
nonsil <- (labs[2:r,5] != "sil" & labs[1:(r-1),5] != "sil")
samefile2 = (samefile[1:(r-2)] & samefile[2:(r-1)])
nonsil2 = (nonsil[1:(r-2)] & nonsil[2:(r-1)])

#Calculates mean change in a formant from frame to frame.
jitter <- function(df, i) {
    mean(abs( (df[2:r,i]-df[1:(r-1),i])[samefile & nonsil] ))
}

##Calculates the percentage of frames in which the formant trajectory changes direction
## (i.e. local minima and maxima).
jitter2 <- function(df, i) {
    dm1=df[1:(r-2),i]
    dp1=df[3:r,i]
    d0=df[2:(r-1),i]
    sum( ((dm1 > d0 & dp1 > d0) | (dm1 < d0 & dp1 < d0))[samefile2 & nonsil2] ) / sum(samefile2 & nonsil2) * 100
}

##Standard deviation of the formant.
jitter3 <- function(df, i) {
    sd(df[,i])
}

##Collects "jitter" values for multiple formants
getjit <- function(df, jfunc, n=length(df)-2) {
    jset=NULL
    for (i in 3:(n+2)) jset=c(jset, jfunc(df, i))
    jset=c(mean(jset), jset)
    jset
}

##Calculates RMSE values for the given data subset, broken down by formant and gender
getRMSE <- function(df, vec) {
  vec = (labs$V5!="sil" & vec)
  fem = (hand$V4 == "f" & vec)
  mal = (hand$V4 == "m" & vec)
  res=sqrt(mean(c((hand[vec,9]-df[vec,3])^2, (hand[vec,10]-df[vec,4])^2, (hand[vec,11]-df[vec,5])^2)))
  res=c(res, sqrt(mean( (hand[vec,]$V9 - df[vec,]$V3)^2 ))) 
  res=c(res, sqrt(mean( (hand[vec,]$V10 - df[vec,]$V4)^2 ))) 
  res=c(res, sqrt(mean( (hand[vec,]$V11 - df[vec,]$V5)^2 ))) 
  res=c(res, sqrt(mean( (hand[fem,]$V9 - df[fem,]$V3)^2 ))) 
  res=c(res, sqrt(mean( (hand[mal,]$V9 - df[mal,]$V3)^2 ))) 
  res=c(res, sqrt(mean( (hand[fem,]$V10 - df[fem,]$V4)^2 ))) 
  res=c(res, sqrt(mean( (hand[mal,]$V10 - df[mal,]$V4)^2 ))) 
  res=c(res, sqrt(mean( (hand[fem,]$V11 - df[fem,]$V5)^2 ))) 
  res=c(res, sqrt(mean( (hand[mal,]$V11 - df[mal,]$V5)^2 ))) 
  res=c(res, sqrt(mean(c((hand[fem,9]-df[fem,3])^2, (hand[fem,10]-df[fem,4])^2, (hand[fem,11]-df[fem,5])^2))))
  res=c(res, sqrt(mean(c((hand[mal,9]-df[mal,3])^2, (hand[mal,10]-df[mal,4])^2, (hand[mal,11]-df[mal,5])^2))))
  res
}

##A smaller set of RMSE values
getRMSEmin <- function(df, vec) {
  vec = (labs$V5!="sil" & vec)
  fem = (hand$V4 == "f" & vec)
  mal = (hand$V4 == "m" & vec)
  res=sqrt(mean(c((hand[vec,9]-df[vec,3])^2, (hand[vec,10]-df[vec,4])^2, (hand[vec,11]-df[vec,5])^2)))
  res=c(res, sqrt(mean( (hand[fem,]$V9 - df[fem,]$V3)^2 ))) 
  res=c(res, sqrt(mean( (hand[mal,]$V9 - df[mal,]$V3)^2 ))) 
  res=c(res, sqrt(mean( (hand[fem,]$V10 - df[fem,]$V4)^2 ))) 
  res=c(res, sqrt(mean( (hand[mal,]$V10 - df[mal,]$V4)^2 ))) 
  res=c(res, sqrt(mean( (hand[fem,]$V11 - df[fem,]$V5)^2 ))) 
  res=c(res, sqrt(mean( (hand[mal,]$V11 - df[mal,]$V5)^2 ))) 
  res
}

##Calculates MAE values broken down by phonetic subclass, for the given data subset.
getMAE <- function(df, vec) {
  vec = (labs$V5!="sil" & vec)
  fem = (hand$V4 == "f" & vec)
  mal = (hand$V4 == "m" & vec)
  res=mean(abs(c(hand[vec,9]-df[vec,3], hand[vec,10]-df[vec,4], hand[vec,11]-df[vec,5] )))
  res=c(res, mean(abs(c(hand[fem,9]-df[fem,3], hand[fem,10]-df[fem,4], hand[fem,11]-df[fem,5] ))))
  res=c(res, mean(abs(c(hand[mal,9]-df[mal,3], hand[mal,10]-df[mal,4], hand[mal,11]-df[mal,5] ))))
  res=c(res, mean(abs( (hand[vec,]$V9 - df[vec,]$V3) ))) 
  res=c(res, mean(abs( (hand[vec,]$V10 - df[vec,]$V4) ))) 
  res=c(res, mean(abs( (hand[vec,]$V11 - df[vec,]$V5) ))) 
  res=c(res, mean(abs( (hand[fem,]$V9 - df[fem,]$V3) ))) 
  res=c(res, mean(abs( (hand[mal,]$V9 - df[mal,]$V3) ))) 
  res=c(res, mean(abs( (hand[fem,]$V10 - df[fem,]$V4) ))) 
  res=c(res, mean(abs( (hand[mal,]$V10 - df[mal,]$V4) ))) 
  res=c(res, mean(abs( (hand[fem,]$V11 - df[fem,]$V5) ))) 
  res=c(res, mean(abs( (hand[mal,]$V11 - df[mal,]$V5) ))) 
  res
}

##A smaller set of MAE values.
getMAEmin <- function(df, vec) {
  vec = (labs$V5!="sil" & vec)
  res=mean(abs(c(hand[vec,9]-df[vec,3], hand[vec,10]-df[vec,4], hand[vec,11]-df[vec,5] )))
  res=c(res, mean(abs( (hand[vec,]$V9 - df[vec,]$V3) ))) 
  res=c(res, mean(abs( (hand[vec,]$V10 - df[vec,]$V4) ))) 
  res=c(res, mean(abs( (hand[vec,]$V11 - df[vec,]$V5) ))) 
  res
}

##Printing values
pprint <- function(df, name, label, func, vec) {
    print(noquote(paste(c(label, sprintf("%4.0f", func(df, vec)), name), collapse=" ")))
}

##Function to generate a complete report for a given model
report <- function(df, name) {
    print(noquote("                 ALL  F1   F2   F3  F1-f F1-m F2-f F2-m F3-f F3-m  fem male"))
    print(noquote("                ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----"))

    pprint(df, name, "RMSE   all all:", getRMSE, vec=(labs$V5!="sil"))
    pprint(df, name, "RMSE vdseg all:", getRMSE, vec=(labs$V4=="vd"))
    pprint(df, name, "RMSE vdfra all:", getRMSE, vec=(plabs$V3=="vd"))
    pprint(df, name, "RMSE vlseg all:", getRMSE, vec=(labs$V4=="vl"))
    pprint(df, name, "RMSE vlfra all:", getRMSE, vec=(plabs$V3=="vl"))
    print("", quote=F)

    pprint(df, name, "RMSE   all tst:", getRMSE, vec=(labs$V5!="sil" & hand$V2=="test"))
    pprint(df, name, "RMSE vdseg tst:", getRMSE, vec=(labs$V4=="vd" & hand$V2=="test"))
    pprint(df, name, "RMSE vdfra tst:", getRMSE, vec=(plabs$V3=="vd" & hand$V2=="test"))
    pprint(df, name, "RMSE vlseg tst:", getRMSE, vec=(labs$V4=="vl" & hand$V2=="test"))
    pprint(df, name, "RMSE vlfra tst:", getRMSE, vec=(plabs$V3=="vl" & hand$V2=="test"))
    print("", quote=F)

    pprint(df, name, "RMSE   all trn:", getRMSE, vec=(labs$V5!="sil" & hand$V2=="train"))
    pprint(df, name, "RMSE vdseg trn:", getRMSE, vec=(labs$V4=="vd" & hand$V2=="train"))
    pprint(df, name, "RMSE vdfra trn:", getRMSE, vec=(plabs$V3=="vd" & hand$V2=="train"))
    pprint(df, name, "RMSE vlseg trn:", getRMSE, vec=(labs$V4=="vl" & hand$V2=="train"))
    pprint(df, name, "RMSE vlfra trn:", getRMSE, vec=(plabs$V3=="vl" & hand$V2=="train"))
    print("", quote=F)

    pprint(df, name, "RMSE  'iy' all:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="iy"))
    pprint(df, name, "RMSE  'ah' all:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="ah"))
    pprint(df, name, "RMSE  'ux' all:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="ux"))
    pprint(df, name, "RMSE  'uw' all:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="uw"))
    pprint(df, name, "RMSE ux|uw all:", getRMSE, vec=(plabs$V3=="vd" & (labs$V3=="ux" | labs$V3=="uw")))
    print("", quote=F)

    pprint(df, name, "RMSE  'iy' tst:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="iy" & hand$V2=="test"))
    pprint(df, name, "RMSE  'ah' tst:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="ah" & hand$V2=="test"))
    pprint(df, name, "RMSE  'ux' tst:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="ux" & hand$V2=="test"))
    pprint(df, name, "RMSE  'uw' tst:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="uw" & hand$V2=="test"))
    pprint(df, name, "RMSE ux|uw tst:", getRMSE, vec=((labs$V3=="ux" | labs$V3=="uw") & plabs$V3=="vd" & hand$V2=="test"))
    print("", quote=F)
    
    pprint(df, name, "RMSE  'iy' trn:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="iy" & hand$V2=="train"))
    pprint(df, name, "RMSE  'ah' trn:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="ah" & hand$V2=="train"))
    pprint(df, name, "RMSE  'ux' trn:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="ux" & hand$V2=="train"))
    pprint(df, name, "RMSE  'uw' trn:", getRMSE, vec=(plabs$V3=="vd" & labs$V3=="uw" & hand$V2=="train"))
    pprint(df, name, "RMSE ux|uw trn:", getRMSE, vec=((labs$V3=="ux" | labs$V3=="uw") & plabs$V3=="vd" & hand$V2=="train"))
    print("", quote=F)
    
    pprint(df, name, " MAE   all all:", getMAE, vec=(labs$V5!="sil"))
    pprint(df, name, " MAE vowel all:", getMAE, vec=(labs$V5=="vow"))
    pprint(df, name, " MAE  semi all:", getMAE, vec=(labs$V5=="semi"))
    pprint(df, name, " MAE nasal all:", getMAE, vec=(labs$V5=="nas"))
    pprint(df, name, " MAE  fric all:", getMAE, vec=(labs$V5=="fric"))
    pprint(df, name, " MAE   aff all:", getMAE, vec=(labs$V5=="aff"))
    pprint(df, name, " MAE  stop all:", getMAE, vec=(labs$V5=="stop"))
    print("", quote=F)

    pprint(df, name, " MAE   all tst:", getMAE, vec=(labs$V5!="sil" & hand$V2=="test"))
    pprint(df, name, " MAE vowel tst:", getMAE, vec=(labs$V5=="vow" & hand$V2=="test"))
    pprint(df, name, " MAE  semi tst:", getMAE, vec=(labs$V5=="semi" & hand$V2=="test"))
    pprint(df, name, " MAE nasal tst:", getMAE, vec=(labs$V5=="nas" & hand$V2=="test"))
    pprint(df, name, " MAE  fric tst:", getMAE, vec=(labs$V5=="fric" & hand$V2=="test"))
    pprint(df, name, " MAE   aff tst:", getMAE, vec=(labs$V5=="aff" & hand$V2=="test"))
    pprint(df, name, " MAE  stop tst:", getMAE, vec=(labs$V5=="stop" & hand$V2=="test"))
    print("", quote=F)

    pprint(df, name, " MAE   all trn:", getMAE, vec=(labs$V5!="sil" & hand$V2=="train"))
    pprint(df, name, " MAE vowel trn:", getMAE, vec=(labs$V5=="vow" & hand$V2=="train"))
    pprint(df, name, " MAE  semi trn:", getMAE, vec=(labs$V5=="semi" & hand$V2=="train"))
    pprint(df, name, " MAE nasal trn:", getMAE, vec=(labs$V5=="nas" & hand$V2=="train"))
    pprint(df, name, " MAE  fric trn:", getMAE, vec=(labs$V5=="fric" & hand$V2=="train"))
    pprint(df, name, " MAE   aff trn:", getMAE, vec=(labs$V5=="aff" & hand$V2=="train"))
    pprint(df, name, " MAE  stop trn:", getMAE, vec=(labs$V5=="stop" & hand$V2=="train"))
    print("", quote=F)

    pprint(df, name, " MAE    si all:", getMAE, vec=(hand$V6=="si"))
    pprint(df, name, " MAE    sx all:", getMAE, vec=(hand$V6=="sx"))
    pprint(df, name, " MAE   dr1 all:", getMAE, vec=(hand$V3=="dr1"))
    pprint(df, name, " MAE   dr2 all:", getMAE, vec=(hand$V3=="dr2"))
    pprint(df, name, " MAE   dr3 all:", getMAE, vec=(hand$V3=="dr3"))
    pprint(df, name, " MAE   dr4 all:", getMAE, vec=(hand$V3=="dr4"))
    pprint(df, name, " MAE   dr5 all:", getMAE, vec=(hand$V3=="dr5"))
    pprint(df, name, " MAE   dr6 all:", getMAE, vec=(hand$V3=="dr6"))
    pprint(df, name, " MAE   dr7 all:", getMAE, vec=(hand$V3=="dr7"))
    pprint(df, name, " MAE   dr8 all:", getMAE, vec=(hand$V3=="dr8"))
    print("", quote=F)

    print(noquote("                 ALL F1-f F1-m F2-f F2-m F3-f F3-m"))
    print(noquote("                ---- ---- ---- ---- ---- ---- ----"))
    pprint(df, name, "mRMS vdfra all:", getRMSEmin, vec=(plabs$V3=="vd"))
    pprint(df, name, "mRMS vdfra tst:", getRMSEmin, vec=(plabs$V3=="vd" & hand$V2=="test"))
    print("", quote=F)

    print(noquote("                 ALL  F1   F2   F3"))
    print(noquote("                ---- ---- ---- ----"))
    pprint(df, name, "mMAE   all tst:", getMAEmin, vec=(labs$V5!="sil" & hand$V2=="test"))
    pprint(df, name, "mMAE vowel tst:", getMAEmin, vec=(labs$V5=="vow" & hand$V2=="test"))
    pprint(df, name, "mMAE  semi tst:", getMAEmin, vec=(labs$V5=="semi" & hand$V2=="test"))
    pprint(df, name, "mMAE nasal tst:", getMAEmin, vec=(labs$V5=="nas" & hand$V2=="test"))
    pprint(df, name, "mMAE  fric tst:", getMAEmin, vec=(labs$V5=="fric" & hand$V2=="test"))
    pprint(df, name, "mMAE   aff tst:", getMAEmin, vec=(labs$V5=="aff" & hand$V2=="test"))
    pprint(df, name, "mMAE  stop tst:", getMAEmin, vec=(labs$V5=="stop" & hand$V2=="test"))
    print("", quote=F)

    print(noquote("                         MEAN    F1     F2     F3"))
    print(noquote("                        -----  -----  -----  -----"))
    print(noquote(paste(c("Standard Deviations:  ", sprintf("%6.1f", getjit(df, jitter3, 3)), name), collapse=" ")))
    print(noquote(paste(c("Mean per-frame diffs: ", sprintf("%6.1f", getjit(df, jitter, 3)), name), collapse=" ")))
    print(noquote(paste(c("Frame % peaks/valleys:", sprintf("%6.1f", getjit(df, jitter2, 3)), name), collapse=" ")))
    print("", quote=F)

    n1 = sum(df$V3 > df$V4)
    n2 = sum(df$V4 > df$V5)
    n3 = sum(df$V5 > df$V6)
    print(noquote("                          Sum  F1>F2  F2>F3  F3>F4"))
    print(sprintf("Frames out of order:   %6d %6d %6d %6d %s", n1+n2+n3, n1, n2, n3, name), quote=F)
    print("", quote=F)

}


##We first generate the variance statistics for all formants (not just the first 3)
##print(noquote("                 MEAN    F1     F2     F3   ..."))
##print(noquote("                -----  -----  -----  -----  ..."))
##print(noquote(paste(c("Overall SDs:  ", sprintf("%6.1f", getjit(df, jitter3)), name), collapse=" ")))
##print(noquote(paste(c("Overall MPFDs:", sprintf("%6.1f", getjit(df, jitter)), name), collapse=" ")))
##print(noquote(paste(c("Overall %PVs: ", sprintf("%6.1f", getjit(df, jitter2)), name), collapse=" ")))
##print("", quote=F)

name1=paste0(" ", name, ".F123")
name0=name1


## The following code checks to see if better results can be obtained by replacing
## one or more of the original formants F1-F3 with any of the higher formants. If a better
## configuration is found, the reports are generated for the amended model,
## rather than the original. The lines for the report will be appended with a suffix
## indicating the new formants used, e.g. "C134" would indicate that formants
## 1, 3, and 4 were used instead of 1-3.

## This was never the case for any of the models we trained with 6 formants. However, with
## models trained on more formants, we often found that the model would insert an
## extra formant between F1 and F2, or between F2 and F3. 


vec=(labs$V5!="sil")
best=10000
N=length(df)
for (i in 3:N)
    for (j in 3:N)
        for (k in 3:N) {
            if (i!=j && j!=k && i!=k) {
                rmse=sqrt(mean(c((hand[vec,9]-df[vec,i])^2, (hand[vec,10]-df[vec,j])^2, (hand[vec,11]-df[vec,k])^2)));
                if (rmse<best) {
                    best=rmse;
                    bestijk=c(i,j,k)
                }
            }
        };

if (sum(bestijk != c(3,4,5)) > 0) {
    df2=df
    df2[,3] = df[,bestijk[1]]
    df2[,4] = df[,bestijk[2]]
    df2[,5] = df[,bestijk[3]]
    name2=paste0(" ", name, ".C")
    for (i in 1:3) name2=paste0(name2, bestijk[i]-2)
    print(noquote(paste("Best corrected model:", name2, "(RMSE", best, ")")))
    print("", quote=F)
    name0=name2
    df=df2
}

## Generate a report for the unsmoothed data.
report(df, paste0(name0, ".s", 0))

## Smooth the data the specified number of rounds, and
## generate a report every _mystep_ rounds as specified.
for (i in 1:smooth) {
    df0=df[,3:5]
    r=nrow(df0)
    dfm1 = rbind(df0[1,], df0[1:(r-1),])
    dfp1 = rbind(df0[2:r,], df0[r,])
    df0 = 0.5*df0 + 0.25*dfm1 + 0.25*dfp1
    df = cbind(df[,1:2], df0)
    if (i %% as.integer(mystep) == 0 || i == smooth)
        report(df, paste0(name0, ".s", i))
}

